import Head from "next/head";
import { GetServerSideProps } from "next/types";
import React from "react";
import { getCategories } from "../jurnalisitk_api/getCategories";
import { GetCategoriesResponse } from "../types";
import { handleSepecialChar } from "../utils/handleSpecialChar";
import Headers from "../components/Headers";
import PostsLists from "../components/PostsLists";
import Footer from "../components/Footer";

type PostsPerCatagoriesProps = {
  categorie: number;
  categories: GetCategoriesResponse[];
  title: string;
};

const PostsPerCatagories: React.FC<PostsPerCatagoriesProps> = props => {
  const { categories, categorie, title } = props;
  return (
    <>
      <Head>
        <title>News Soerjo | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col overflow-hidden justify-center items-center relative">
        <Headers categories={categories} />
        <PostsLists
          categories={categories}
          categorie={categorie}
          title={title}
        />
        <Footer />
      </main>
    </>
  );
};

export default PostsPerCatagories;

export const getServerSideProps: GetServerSideProps = async context => {
  const query = context.query["categories"] as string;
  const getCategoriesName = await getCategories();
  const categoriesName = getCategoriesName.find(
    _cat => handleSepecialChar(_cat.name).toLowerCase() === query
  );

  if (!categoriesName) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }

  const categories = await getCategories();
  return {
    props: {
      categories,
      categorie: categoriesName.id,
      title: handleSepecialChar(categoriesName.name),
    },
  };
};
