import Head from "next/head";
import { GetServerSideProps } from "next/types";
import React from "react";
import { getCategories } from "../jurnalisitk_api/getCategories";
import { GetCategoriesResponse } from "../types";
import { handleSepecialChar } from "../utils/handleSpecialChar";
import Headers from "../components/Headers";
import PostsLists from "../components/PostsLists";
import Footer from "../components/Footer";

type SearchPageProps = {
  categorie?: number;
  categories: GetCategoriesResponse[];
  title: string;
  search: string;
};

const SearchPage: React.FC<SearchPageProps> = props => {
  const { categories, categorie, title, search } = props;
  return (
    <>
      <Head>
        <title>News Soerjo | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col overflow-hidden justify-center items-center relative">
        <Headers categories={categories} />
        <PostsLists
          categories={categories}
          categorie={categorie}
          title={title}
          search={search}
        />
        <Footer />
      </main>
    </>
  );
};

export default SearchPage;

export const getServerSideProps: GetServerSideProps = async context => {
  const search = context.query["q"];
  const categories = await getCategories();
  console.log(search);

  return {
    props: {
      categories,
      search,
      title: `Search: "${search}"`,
    },
  };
};
